# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NPO'),
        ),
    ]
